version: '3.8'

services: 
  postgres: 
    container_name: nest-clean-pg
    image: postgres
    port: 
      - 5432:5432
    entrypoint: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-clean
      PG_DATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres